Repository alfa-laboratory/core-components, pull requests merged in 2020-08, with the labels that each got.

#220 Feat/typography
  package.json
  packages/typography/package.json
  packages/typography/src/Component.stories.mdx
  packages/typography/src/Component.tsx
  packages/typography/src/colors.module.css
  packages/typography/src/colors.ts
  packages/typography/src/index.ts
  packages/typography/src/text/Component.test.tsx
  packages/typography/src/text/Component.tsx
  packages/typography/src/text/index.module.css
  packages/typography/src/text/index.ts
  packages/typography/src/title/Component.test.tsx
  packages/typography/src/title/Component.tsx
  packages/typography/src/title/index.module.css
  packages/typography/src/title/index.ts
  packages/typography/tsconfig.json
  packages/vars/src/typography.css
  yarn.lock
Labels: Candidate Recommendation

#237 fix: fix import example
  packages/typography/src/Component.stories.mdx
Labels: Bug, Documentation

#231 Feat/add use focus hook
  package.json
  packages/button/package.json
  packages/button/src/Component.tsx
  packages/checkbox/package.json
  packages/checkbox/src/Component.tsx
  packages/checkbox/src/index.module.css
  packages/keyboard-focusable/src/Component.stories.mdx
  packages/keyboard-focusable/src/Component.tsx
  packages/link/package.json
  packages/link/src/Component.tsx
  packages/link/src/index.module.css
  packages/radio/package.json
  packages/radio/src/Component.tsx
  packages/radio/src/index.module.css
  packages/switch/package.json
  packages/switch/src/Component.tsx
  packages/switch/src/index.module.css
  packages/tabs/package.json
  packages/tabs/src/Component.stories.mdx
  packages/tabs/src/components/primary-tablist/Component.tsx
  packages/tabs/src/components/primary-tablist/index.module.css
  packages/tabs/src/components/secondary-tablist/index.module.css
  packages/tabs/src/useTabs.tsx
  packages/tabs/tsconfig.json
  packages/tag/package.json
  packages/tag/src/Component.tsx
  packages/tag/src/index.module.css
  yarn.lock
Labels: Enhancement
