Repository alfa-laboratory/core-components, pull requests merged in 2020-12, with the labels that each got.

#402 fix(mq): use addListener and removeListener
  packages/mq/src/Component.test.tsx
  packages/mq/src/useMatchMedia.test.tsx
  packages/mq/src/useMatchMedia.tsx
  packages/select/src/components/arrow/index.module.css
Labels: Bug

#436 feat(select): add exporting select utils
  packages/select/src/index.ts
Labels: Minor

#437 fix: change icons imports paths
  packages/attach/src/Component.tsx
  packages/bank-card/src/Component.tsx
  packages/notification/src/Component.tsx
  packages/picker-button/src/field/Component.tsx
  rollup.config.js
Labels: Patch

#441 fix(calendar): set max date to years calculation
  packages/calendar/src/useCalendar.ts
  packages/calendar/src/utils.ts
Labels: Patch

#427 feat(space): add space component
  packages/space/package.json
  packages/space/src/Component.stories.mdx
  packages/space/src/Component.test.tsx
  packages/space/src/Component.tsx
  packages/space/src/Item.tsx
  packages/space/src/__snapshots__/Component.test.tsx.snap
  packages/space/src/index.module.css
  packages/space/src/index.ts
  packages/space/src/utils.ts
  packages/space/tsconfig.json
Labels: Draft, Enhancement, Minor

#444 feat: change form-control styles
  packages/bank-card/src/index.module.css
  packages/form-control/src/index.module.css
  packages/pure-input/src/index.module.css
  packages/textarea/src/Component.tsx
  packages/textarea/src/index.module.css
  packages/themes/src/mixins/form-control/click.css
  packages/themes/src/mixins/form-control/site.css
  packages/themes/src/mixins/site.css
Labels: Major

#446 feat(typography): add default margins
  packages/typography/src/component.stories.mdx
  packages/typography/src/margins.module.css
  packages/typography/src/title-responsive/component.tsx
  packages/typography/src/title-responsive/index.module.css
  packages/typography/src/title/component.tsx
  packages/typography/src/title/index.module.css
  packages/typography/src/title/index.tsx
Labels: Minor

#445 feat(input-autocomplete): dont close popover on input click
  packages/select/src/components/base-select/Component.tsx
Labels: Minor

#426 feat(calendar-range): add component
  packages/calendar-input/src/Component.tsx
  packages/calendar-range/package.json
  packages/calendar-range/src/Component.stories.mdx
  packages/calendar-range/src/Component.test.tsx
  packages/calendar-range/src/Component.tsx
  packages/calendar-range/src/__snapshots__/Component.test.tsx.snap
  packages/calendar-range/src/index.module.css
  packages/calendar-range/src/index.ts
  packages/calendar-range/src/utils.ts
  packages/calendar-range/tsconfig.json
  packages/calendar/src/usePeriod.ts
Labels: Minor

#449 fix(themes): add missing variables import
  packages/themes/src/default.css
Labels: Patch

#443 fix(tooltip): execute tooltip's target missing callbacks
  packages/tooltip/src/Component.test.tsx
  packages/tooltip/src/Component.tsx
Labels: Patch

#416 feat(checkbox, radio): size m
  packages/checkbox-group/src/__snapshots__/Component.test.tsx.snap
  packages/checkbox/src/Component.stories.mdx
  packages/checkbox/src/Component.test.tsx
  packages/checkbox/src/Component.tsx
  packages/checkbox/src/__snapshots__/Component.test.tsx.snap
  packages/checkbox/src/index.module.css
  packages/radio-group/src/__snapshots__/Component.test.tsx.snap
  packages/radio/src/Component.stories.mdx
  packages/radio/src/Component.test.tsx
  packages/radio/src/Component.tsx
  packages/radio/src/__snapshots__/Component.test.tsx.snap
  packages/radio/src/index.module.css
Labels: Minor

#439 feat(collapse): add collapse component
  packages/collapse/package.json
  packages/collapse/src/Component.stories.mdx
  packages/collapse/src/Component.test.tsx
  packages/collapse/src/Component.tsx
  packages/collapse/src/__snapshots__/Component.test.tsx.snap
  packages/collapse/src/index.module.css
  packages/collapse/src/index.ts
  packages/collapse/tsconfig.json
Labels: Enhancement, Minor

#456 fix(divider): missed vars
  packages/divider/src/index.module.css
Labels: Patch

#452 fix(themes): fixed click select theme
  packages/select/src/components/option/index.module.css
  packages/themes/src/mixins/select/click.css
Labels: Patch

#457 feat(link): simplify link without addons
  packages/link/src/Component.stories.mdx
  packages/link/src/Component.tsx
  packages/link/src/__snapshots__/Component.test.tsx.snap
  packages/link/src/index.module.css
Labels: Minor

#454 feat(picker-button): simplify picker-button using colorless icons
  package.json
  packages/button/src/Component.stories.mdx
  packages/picker-button/src/__snapshots__/Component.test.tsx.snap
  packages/picker-button/src/field/Component.tsx
  packages/picker-button/src/field/index.module.css
  yarn.lock
Labels: Minor

#453 feat(themes): fixed click theme for tag
  packages/themes/src/mixins/tag/click.css
Labels: Patch

#451 feat(themes): --arrow-transform var with click theme
  packages/picker-button/src/field/index.module.css
  packages/plate/src/index.module.css
  packages/select/src/components/arrow/index.module.css
  packages/themes/src/default.css
  packages/themes/src/mixins/click.css
Labels: Minor

#438 feat(select): add empty list placeholder prop
  packages/select/src/components/base-select/Component.tsx
  packages/select/src/components/options-list/Component.tsx
  packages/select/src/components/options-list/index.module.css
  packages/select/src/components/virtual-options-list/Component.tsx
  packages/select/src/components/virtual-options-list/index.module.css
  packages/select/src/typings.ts
  packages/select/src/vars.css
Labels: Minor

#435 feat(select-with-tags): add select with tags
  packages/select-with-tags/package.json
  packages/select-with-tags/src/__snapshots__/component.test.tsx.snap
  packages/select-with-tags/src/component.stories.mdx
  packages/select-with-tags/src/component.test.tsx
  packages/select-with-tags/src/component.tsx
  packages/select-with-tags/src/components/index.ts
  packages/select-with-tags/src/components/tag-list/component.tsx
  packages/select-with-tags/src/components/tag-list/index.module.css
  packages/select-with-tags/src/components/tag-list/index.ts
  packages/select-with-tags/src/index.ts
  packages/select-with-tags/src/types.ts
  packages/select-with-tags/src/utils/index.ts
  packages/select-with-tags/src/utils/match.test.ts
  packages/select-with-tags/src/utils/match.ts
  packages/select-with-tags/tsconfig.json
  yarn.lock
Labels: Minor

#412 feat(modal): add modal
  babel.config.js
  package.json
  packages/modal/package.json
  packages/modal/src/Component.manager.test.ts
  packages/modal/src/Component.manager.ts
  packages/modal/src/Component.stories.mdx
  packages/modal/src/Component.test.tsx
  packages/modal/src/Component.tsx
  packages/modal/src/components/backdrop/Component.tsx
  packages/modal/src/components/backdrop/index.module.css
  packages/modal/src/components/backdrop/index.ts
  packages/modal/src/components/fade/Component.test.tsx
  packages/modal/src/components/fade/Component.tsx
  packages/modal/src/components/fade/index.module.css
  packages/modal/src/components/fade/index.ts
  packages/modal/src/components/fade/utils.ts
  packages/modal/src/index.module.css
  packages/modal/src/index.ts
  packages/modal/src/utils.ts
  packages/modal/tsconfig.json
  packages/portal/src/Component.test.tsx
  packages/portal/src/Component.tsx
  packages/portal/src/utils.ts
  packages/trap-focus/package.json
  packages/trap-focus/src/Component.test.tsx
  packages/trap-focus/src/Component.tsx
  packages/trap-focus/src/index.ts
  packages/trap-focus/tsconfig.json
  packages/vars/src/index.css
  yarn.lock
Labels: Minor

#428 feat(select): popoverPosition, render to body, test issues
  .storybook/public/global.css
  packages/intl-phone-input/src/__snapshots__/component.test.tsx.snap
  packages/intl-phone-input/src/component.tsx
  packages/intl-phone-input/src/components/select/component.tsx
  packages/picker-button/src/Component.stories.mdx
  packages/picker-button/src/Component.test.tsx
  packages/picker-button/src/Component.tsx
  packages/picker-button/src/__snapshots__/Component.test.tsx.snap
  packages/picker-button/src/field/Component.tsx
  packages/select-with-tags/src/__snapshots__/component.test.tsx.snap
  packages/select/src/Component.stories.mdx
  packages/select/src/__snapshots__/Component.test.tsx.snap
  packages/select/src/components/base-select/Component.tsx
  packages/select/src/components/base-select/index.module.css
  packages/select/src/components/field/Component.tsx
  packages/select/src/components/option/Component.tsx
  packages/select/src/components/options-list/Component.tsx
  packages/select/src/components/virtual-options-list/Component.tsx
  packages/select/src/typings.ts
  packages/select/src/utils.ts
  packages/select/tsconfig.json
  packages/utils/getDataTestId.ts
  packages/utils/index.ts
Labels: Major

#459 feat: read-only state
  packages/amount-input/src/Component.stories.mdx
  packages/calendar-input/src/Component.stories.mdx
  packages/calendar-input/src/Component.tsx
  packages/calendar-range/src/Component.test.tsx
  packages/calendar-range/src/__snapshots__/Component.test.tsx.snap
  packages/input-autocomplete/src/Component.tsx
  packages/input-autocomplete/src/autocomplete-field/Component.tsx
  packages/input/src/Component.stories.mdx
  packages/input/src/index.module.css
  packages/intl-phone-input/src/component.stories.mdx
  packages/intl-phone-input/src/component.tsx
  packages/slider-input/src/Component.stories.mdx
  packages/slider-input/src/Component.tsx
  packages/textarea/src/Component.stories.mdx
  packages/textarea/src/index.module.css
  packages/themes/src/default.css
  packages/themes/src/mixins/input/click.css
  packages/with-suffix/src/Component.stories.mdx
  packages/with-suffix/src/Component.tsx
  packages/with-suffix/src/index.module.css
Labels: Minor
