Repository alfa-laboratory/core-components, pull requests merged in 2021-01, with the labels that each got.

#462 fix(input): set aria-label attr when label passed
  packages/bank-card/src/__snapshots__/Component.test.tsx.snap
  packages/input/src/Component.test.tsx
  packages/input/src/Component.tsx
Labels: Patch

#474 fix(calendar): fix years-table position
  packages/calendar/src/components/years-table/index.module.css
Labels: Patch

#471 feat(calendar): add scrolling to selected year when open year select
  packages/calendar/src/Component.tsx
  packages/calendar/src/components/years-table/Component.tsx
Labels: Minor

#473 fix(input-autocomplete): fix mousedown issue
  packages/input-autocomplete/src/autocomplete-field/Component.tsx
Labels: Patch

#465 fix style for form-control and base-select
  packages/form-control/src/index.module.css
  packages/select/src/components/base-select/index.module.css
Labels: Bug, Patch

#466 feat: improve radio, checkbox and switch components
  packages/checkbox-group/src/__snapshots__/Component.test.tsx.snap
  packages/checkbox/src/Component.stories.mdx
  packages/checkbox/src/Component.tsx
  packages/checkbox/src/__snapshots__/Component.test.tsx.snap
  packages/checkbox/src/index.module.css
  packages/radio-group/src/__snapshots__/Component.test.tsx.snap
  packages/radio/src/Component.stories.mdx
  packages/radio/src/Component.tsx
  packages/radio/src/__snapshots__/Component.test.tsx.snap
  packages/radio/src/index.module.css
  packages/switch/src/Component.stories.mdx
  packages/switch/src/Component.tsx
  packages/switch/src/__snapshots__/Component.test.tsx.snap
  packages/switch/src/index.module.css
Labels: Enhancement, Minor

#468 fix(input): prevent autocomplete to change bgcolor
  packages/input/src/index.module.css
Labels: Patch

#461 feat: add stylelint-core-vars
  package.json
  packages/badge/src/index.module.css
  packages/bank-card/src/index.module.css
  packages/calendar/src/components/days-table/index.module.css
  packages/calendar/src/components/header/index.module.css
  packages/skeleton/src/stories.module.css
  packages/tag/src/index.module.css
  yarn.lock
Labels: Patch

#467 feat: add fieldClassName
  packages/amount-input/src/__snapshots__/Component.test.tsx.snap
  packages/bank-card/src/__snapshots__/Component.test.tsx.snap
  packages/calendar-input/src/__snapshots__/Component.test.tsx.snap
  packages/calendar-range/src/__snapshots__/Component.test.tsx.snap
  packages/form-control/src/Component.test.tsx
  packages/form-control/src/Component.tsx
  packages/input/src/Component.test.tsx
  packages/input/src/Component.tsx
  packages/input/src/__snapshots__/Component.test.tsx.snap
  packages/intl-phone-input/src/__snapshots__/component.test.tsx.snap
  packages/masked-input/src/__snapshots__/Component.test.tsx.snap
  packages/phone-input/src/__snapshots__/Component.test.tsx.snap
  packages/select-with-tags/src/components/tag-list/component.tsx
  packages/select/src/components/field/Component.tsx
  packages/slider-input/src/__snapshots__/Component.test.tsx.snap
  packages/textarea/src/Component.test.tsx
  packages/textarea/src/Component.tsx
  packages/with-suffix/src/__snapshots__/Component.test.tsx.snap
Labels: Major

#484 feat(amount-input): delete zero minor part in passed amount
  packages/amount-input/src/Component.test.tsx
  packages/amount-input/src/Component.tsx
  packages/amount-input/src/utils/index.ts
Labels: Enhancement
