Repository alfa-laboratory/core-components, pull requests merged in 2021-02, with the labels that each got.

#493 fix(phone-input): fix caret
  packages/phone-input/src/Component.tsx
Labels: Bug

#482 docs: theming.stories.mdx
  docs/2.theming.stories.mdx
Labels: Documentation

#472 feat(select-with-tags): design review fixes
  packages/select-with-tags/package.json
  packages/select-with-tags/src/__snapshots__/component.test.tsx.snap
  packages/select-with-tags/src/component.stories.mdx
  packages/select-with-tags/src/component.tsx
  packages/select-with-tags/src/components/index.ts
  packages/select-with-tags/src/components/tag-list/component.tsx
  packages/select-with-tags/src/components/tag-list/index.module.css
  packages/select-with-tags/src/components/tag/component.tsx
  packages/select-with-tags/src/components/tag/index.module.css
  packages/select-with-tags/src/components/tag/index.ts
  packages/select-with-tags/src/types.ts
  packages/select/src/components/base-select/Component.tsx
  yarn.lock
Labels: Minor

#499 feat(badge): reinvented icon view, visibleIconOutline and better docs
  .storybook/blocks/grid/Col.css
  .storybook/blocks/grid/Row.tsx
  package.json
  packages/badge/src/Component.stories.mdx
  packages/badge/src/Component.test.tsx
  packages/badge/src/Component.tsx
  packages/badge/src/index.module.css
  yarn.lock
Labels: Major

#500 feat(button): updated button colors and themes
  .storybook/addons/theme-switcher/index.css
  .storybook/public/global.css
  packages/button/src/Component.stories.mdx
  packages/button/src/index.module.css
  packages/themes/src/mixins/button/corp-inverted.css
  packages/themes/src/mixins/button/corp.css
  packages/themes/src/mixins/button/site-inverted.css
  packages/themes/src/mixins/button/site.css
  packages/themes/src/mixins/site-inverted.css
  packages/themes/src/mixins/site.css
Labels: Minor

#503 fix: control colors (PDS-199)
  packages/form-control/src/index.module.css
  packages/select-with-tags/src/components/tag-list/index.module.css
Labels: Patch

#486 feat(grid): add component
  .storybook/public/global.css
  bin/purgecss.js
  bin/purgecss.sh
  package.json
  packages/grid/package.json
  packages/grid/src/Component.stories.mdx
  packages/grid/src/Component.tsx
  packages/grid/src/col/Component.test.tsx
  packages/grid/src/col/Component.tsx
  packages/grid/src/col/__snapshots__/Component.test.tsx.snap
  packages/grid/src/col/index.module.css
  packages/grid/src/col/index.tsx
  packages/grid/src/gutters.module.css
  packages/grid/src/index.ts
  packages/grid/src/row/Component.test.tsx
  packages/grid/src/row/Component.tsx
  packages/grid/src/row/__snapshots__/Component.test.tsx.snap
  packages/grid/src/row/index.module.css
  packages/grid/src/row/index.tsx
  packages/grid/src/typings.ts
  packages/grid/src/utils/index.test.tsx
  packages/grid/src/utils/index.ts
  packages/grid/tsconfig.json
  postcss.config.js
  yarn.lock
Labels: Minor

#502 feat: improve read-only behaviour (PDS-200)
  packages/input-autocomplete/src/autocomplete-field/Component.tsx
  packages/input/src/Component.tsx
  packages/input/src/index.module.css
  packages/with-suffix/src/index.module.css
Labels: Minor

#509 fix(plate): fixed --arrow-transform var, tuned transition
  packages/plate/src/index.module.css
  packages/themes/src/default.css
Labels: Patch

#505 feat(icon-button): add component
  packages/icon-button/package.json
  packages/icon-button/src/Component.stories.mdx
  packages/icon-button/src/Component.test.tsx
  packages/icon-button/src/Component.tsx
  packages/icon-button/src/__snapshots__/Component.test.tsx.snap
  packages/icon-button/src/index.module.css
  packages/icon-button/src/index.ts
  packages/icon-button/tsconfig.json
Labels: Minor

#514 feat(toast-plate): add action button theming, fix addons align
  packages/button/src/Component.stories.mdx
  packages/button/src/index.module.css
  packages/themes/src/mixins/toast-plate/click.css
  packages/toast-plate/src/component.tsx
  packages/toast-plate/src/index.module.css
Labels: Minor

#513 feat(tabs): disabled view
  packages/tabs/src/Component.stories.mdx
  packages/tabs/src/components/primary-tablist/Component.tsx
  packages/tabs/src/components/primary-tablist/index.module.css
  packages/tabs/src/components/tab/Component.tsx
  packages/tabs/src/components/tabs/Component.tsx
  packages/tabs/src/components/tabs/__snapshots__/Component.test.tsx.snap
  packages/tabs/src/typings.ts
  packages/tabs/src/useTabs.tsx
  packages/tabs/src/vars.css
Labels: Minor

#506 feat(select): add visible-options
  packages/picker-button/src/__snapshots__/Component.test.tsx.snap
  packages/select/src/Component.stories.mdx
  packages/select/src/components/base-select/Component.tsx
  packages/select/src/components/options-list/Component.tsx
  packages/select/src/components/options-list/index.module.css
  packages/select/src/components/virtual-options-list/Component.tsx
  packages/select/src/components/virtual-options-list/index.module.css
  packages/select/src/typings.ts
  packages/select/src/utils.ts
  packages/select/src/vars.css
Labels: Minor

#511 feat(select-with-tags): added collapsed tag list
  packages/select-with-tags/src/component.stories.mdx
  packages/select-with-tags/src/component.tsx
  packages/select-with-tags/src/components/tag-list/component.tsx
  packages/select-with-tags/src/components/tag/component.tsx
  packages/select-with-tags/src/components/tag/index.module.css
  packages/select-with-tags/src/types.ts
  packages/select-with-tags/src/utils/calculate-collapse-size.ts
Labels: Minor

#489 refactor(modal): refactor & styles
  package.json
  packages/modal/package.json
  packages/modal/src/Component.desktop.tsx
  packages/modal/src/Component.manager.test.ts
  packages/modal/src/Component.manager.ts
  packages/modal/src/Component.mobile.tsx
  packages/modal/src/Component.responsive.tsx
  packages/modal/src/Component.stories.mdx
  packages/modal/src/Component.test.tsx
  packages/modal/src/Component.tsx
  packages/modal/src/components/backdrop/Component.tsx
  packages/modal/src/components/backdrop/index.module.css
  packages/modal/src/components/backdrop/index.ts
  packages/modal/src/components/closer/Component.tsx
  packages/modal/src/components/closer/index.module.css
  packages/modal/src/components/content/Component.desktop.tsx
  packages/modal/src/components/content/Component.mobile.tsx
  packages/modal/src/components/content/Component.tsx
  packages/modal/src/components/content/desktop.module.css
  packages/modal/src/components/content/index.module.css
  packages/modal/src/components/content/mobile.module.css
  packages/modal/src/components/fade/Component.test.tsx
  packages/modal/src/components/fade/Component.tsx
  packages/modal/src/components/fade/index.module.css
  packages/modal/src/components/fade/index.ts
  packages/modal/src/components/fade/utils.ts
  packages/modal/src/components/footer/Component.desktop.tsx
  packages/modal/src/components/footer/Component.mobile.tsx
  packages/modal/src/components/footer/Component.tsx
  packages/modal/src/components/footer/desktop.module.css
  packages/modal/src/components/footer/index.module.css
  packages/modal/src/components/footer/mobile.module.css
  packages/modal/src/components/header/Component.desktop.tsx
  packages/modal/src/components/header/Component.mobile.tsx
  packages/modal/src/components/header/Component.tsx
  packages/modal/src/components/header/desktop.module.css
  packages/modal/src/components/header/index.module.css
  packages/modal/src/components/header/mobile.module.css
  packages/modal/src/desktop.module.css
  packages/modal/src/desktop.ts
  packages/modal/src/index.module.css
  packages/modal/src/mobile.ts
  packages/modal/src/responsive.ts
  packages/modal/src/transitions/backdrop.module.css
  packages/modal/src/transitions/content.module.css
  packages/modal/src/utils.ts
  packages/modal/src/vars.css
  packages/modal/tsconfig.json
  packages/themes/src/mixins/click.css
  packages/themes/src/mixins/modal/click.css
  packages/trap-focus/package.json
  packages/trap-focus/src/Component.test.tsx
  packages/trap-focus/src/Component.tsx
  packages/trap-focus/src/index.ts
  packages/trap-focus/tsconfig.json
  yarn.lock
Labels: Minor

#497 feat(drawer): add component
  packages/drawer/package.json
  packages/drawer/src/Component.stories.mdx
  packages/drawer/src/Component.test.tsx
  packages/drawer/src/Component.tsx
  packages/drawer/src/__snapshots__/Component.test.tsx.snap
  packages/drawer/src/index.module.css
  packages/drawer/src/index.ts
  packages/drawer/tsconfig.json
Labels: Minor
